// Code generated by Slice Machine. DO NOT EDIT.

import BlogSlice from './BlogSlice/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	blog_slice: BlogSlice,
	rich_text: RichText
};
